//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.29 at 11:26:11 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.omg.org/spec/DD/20100524/DI", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.omg.spec.dd._20100524.di;
