//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.19 at 04:14:13 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.opengroup.org/xsd/archimate/3.0/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.opengroup.xsd.archimate._3;
