//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.09 at 09:51:24 PM CET 
//


package org.opengroup.xsd.archimate._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Access complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Access">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengroup.org/xsd/archimate/3.0/}RelationshipType">
 *       &lt;attribute name="accessDirection" type="{http://www.opengroup.org/xsd/archimate/3.0/}AccessDirectionEnum" default="Access" />
 *       &lt;anyAttribute namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Access")
public class Access
    extends RelationshipType
{

    @XmlAttribute(name = "accessDirection")
    protected AccessDirectionEnum accessDirection;

    /**
     * Gets the value of the accessDirection property.
     * 
     * @return
     *     possible object is
     *     {@link AccessDirectionEnum }
     *     
     */
    public AccessDirectionEnum getAccessDirection() {
        if (accessDirection == null) {
            return AccessDirectionEnum.ACCESS;
        } else {
            return accessDirection;
        }
    }

    /**
     * Sets the value of the accessDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccessDirectionEnum }
     *     
     */
    public void setAccessDirection(AccessDirectionEnum value) {
        this.accessDirection = value;
    }

}
