//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.19 at 04:14:13 PM CET 
//


package org.opengroup.xsd.archimate._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 This is a container for all of the Views in the model.
 *             
 * 
 * <p>Java class for ViewsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ViewsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="viewpoints" type="{http://www.opengroup.org/xsd/archimate/3.0/}ViewpointsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ViewsType", propOrder = {
    "viewpoints"
})
public class ViewsType {

    protected ViewpointsType viewpoints;

    /**
     * Gets the value of the viewpoints property.
     * 
     * @return
     *     possible object is
     *     {@link ViewpointsType }
     *     
     */
    public ViewpointsType getViewpoints() {
        return viewpoints;
    }

    /**
     * Sets the value of the viewpoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link ViewpointsType }
     *     
     */
    public void setViewpoints(ViewpointsType value) {
        this.viewpoints = value;
    }

}
