//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.22 at 11:27:57 PM CEST 
//


package disco;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ProcessMap.Nodes.StartNode.Layout }
     * 
     */
    public ProcessMap.Nodes.StartNode.Layout createProcessMapNodesStartNodeLayout() {
        return new ProcessMap.Nodes.StartNode.Layout();
    }

    /**
     * Create an instance of {@link ProcessMap.Edges.Edge.Layout }
     * 
     */
    public ProcessMap.Edges.Edge.Layout createProcessMapEdgesEdgeLayout() {
        return new ProcessMap.Edges.Edge.Layout();
    }

    /**
     * Create an instance of {@link ProcessMap.Nodes.Node }
     * 
     */
    public ProcessMap.Nodes.Node createProcessMapNodesNode() {
        return new ProcessMap.Nodes.Node();
    }

    /**
     * Create an instance of {@link ProcessMap.Edges.Edge.Frequency }
     * 
     */
    public ProcessMap.Edges.Edge.Frequency createProcessMapEdgesEdgeFrequency() {
        return new ProcessMap.Edges.Edge.Frequency();
    }

    /**
     * Create an instance of {@link ProcessMap.Nodes.EndNode.Layout }
     * 
     */
    public ProcessMap.Nodes.EndNode.Layout createProcessMapNodesEndNodeLayout() {
        return new ProcessMap.Nodes.EndNode.Layout();
    }

    /**
     * Create an instance of {@link ProcessMap.Nodes }
     * 
     */
    public ProcessMap.Nodes createProcessMapNodes() {
        return new ProcessMap.Nodes();
    }

    /**
     * Create an instance of {@link ProcessMap.Edges }
     * 
     */
    public ProcessMap.Edges createProcessMapEdges() {
        return new ProcessMap.Edges();
    }

    /**
     * Create an instance of {@link ProcessMap.Edges.Edge.Duration }
     * 
     */
    public ProcessMap.Edges.Edge.Duration createProcessMapEdgesEdgeDuration() {
        return new ProcessMap.Edges.Edge.Duration();
    }

    /**
     * Create an instance of {@link ProcessMap }
     * 
     */
    public ProcessMap createProcessMap() {
        return new ProcessMap();
    }

    /**
     * Create an instance of {@link ProcessMap.Nodes.Node.Duration }
     * 
     */
    public ProcessMap.Nodes.Node.Duration createProcessMapNodesNodeDuration() {
        return new ProcessMap.Nodes.Node.Duration();
    }

    /**
     * Create an instance of {@link ProcessMap.Layout }
     * 
     */
    public ProcessMap.Layout createProcessMapLayout() {
        return new ProcessMap.Layout();
    }

    /**
     * Create an instance of {@link ProcessMap.Nodes.EndNode }
     * 
     */
    public ProcessMap.Nodes.EndNode createProcessMapNodesEndNode() {
        return new ProcessMap.Nodes.EndNode();
    }

    /**
     * Create an instance of {@link ProcessMap.Edges.Edge }
     * 
     */
    public ProcessMap.Edges.Edge createProcessMapEdgesEdge() {
        return new ProcessMap.Edges.Edge();
    }

    /**
     * Create an instance of {@link ProcessMap.Nodes.Node.Layout }
     * 
     */
    public ProcessMap.Nodes.Node.Layout createProcessMapNodesNodeLayout() {
        return new ProcessMap.Nodes.Node.Layout();
    }

    /**
     * Create an instance of {@link ProcessMap.Nodes.StartNode }
     * 
     */
    public ProcessMap.Nodes.StartNode createProcessMapNodesStartNode() {
        return new ProcessMap.Nodes.StartNode();
    }

    /**
     * Create an instance of {@link ProcessMap.Nodes.Node.Frequency }
     * 
     */
    public ProcessMap.Nodes.Node.Frequency createProcessMapNodesNodeFrequency() {
        return new ProcessMap.Nodes.Node.Frequency();
    }

}
