//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.22 at 11:27:57 PM CEST 
//


package disco;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Layout">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}double" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Nodes">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Node" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Frequency">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="total" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="case" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="start" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="end" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="maxRepetitions" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Duration">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="total" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="min" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="mean" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="median" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Layout">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                     &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                     &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                     &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="activity" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="StartNode">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Layout">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                     &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                     &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                     &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="EndNode">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Layout">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                     &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                     &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                     &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="size" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Edges">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Edge" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Frequency">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="total" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="case" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="maxRepetitions" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Duration">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="total" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="min" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="mean" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="median" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Layout">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="curve" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="labelX" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                     &lt;attribute name="labelY" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="sourceIndex" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="targetIndex" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="size" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="numNodes" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="nodeThreshold" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="edgeThreshold" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="discoVersion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "layout",
    "nodes",
    "edges"
})
@XmlRootElement(name = "ProcessMap")
public class ProcessMap {

    @XmlElement(name = "Layout", required = true)
    protected ProcessMap.Layout layout;
    @XmlElement(name = "Nodes", required = true)
    protected ProcessMap.Nodes nodes;
    @XmlElement(name = "Edges", required = true)
    protected ProcessMap.Edges edges;
    @XmlAttribute(name = "numNodes")
    protected Integer numNodes;
    @XmlAttribute(name = "nodeThreshold")
    protected Integer nodeThreshold;
    @XmlAttribute(name = "edgeThreshold")
    protected Integer edgeThreshold;
    @XmlAttribute(name = "discoVersion")
    protected String discoVersion;

    /**
     * Gets the value of the layout property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessMap.Layout }
     *     
     */
    public ProcessMap.Layout getLayout() {
        return layout;
    }

    /**
     * Sets the value of the layout property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessMap.Layout }
     *     
     */
    public void setLayout(ProcessMap.Layout value) {
        this.layout = value;
    }

    /**
     * Gets the value of the nodes property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessMap.Nodes }
     *     
     */
    public ProcessMap.Nodes getNodes() {
        return nodes;
    }

    /**
     * Sets the value of the nodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessMap.Nodes }
     *     
     */
    public void setNodes(ProcessMap.Nodes value) {
        this.nodes = value;
    }

    /**
     * Gets the value of the edges property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessMap.Edges }
     *     
     */
    public ProcessMap.Edges getEdges() {
        return edges;
    }

    /**
     * Sets the value of the edges property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessMap.Edges }
     *     
     */
    public void setEdges(ProcessMap.Edges value) {
        this.edges = value;
    }

    /**
     * Gets the value of the numNodes property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumNodes() {
        return numNodes;
    }

    /**
     * Sets the value of the numNodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumNodes(Integer value) {
        this.numNodes = value;
    }

    /**
     * Gets the value of the nodeThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNodeThreshold() {
        return nodeThreshold;
    }

    /**
     * Sets the value of the nodeThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNodeThreshold(Integer value) {
        this.nodeThreshold = value;
    }

    /**
     * Gets the value of the edgeThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEdgeThreshold() {
        return edgeThreshold;
    }

    /**
     * Sets the value of the edgeThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEdgeThreshold(Integer value) {
        this.edgeThreshold = value;
    }

    /**
     * Gets the value of the discoVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscoVersion() {
        return discoVersion;
    }

    /**
     * Sets the value of the discoVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscoVersion(String value) {
        this.discoVersion = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Edge" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Frequency">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="total" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="case" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="maxRepetitions" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Duration">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="total" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="min" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="mean" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="median" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Layout">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="curve" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="labelX" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                           &lt;attribute name="labelY" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="sourceIndex" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="targetIndex" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="size" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "edge"
    })
    public static class Edges {

        @XmlElement(name = "Edge", required = true)
        protected List<ProcessMap.Edges.Edge> edge;
        @XmlAttribute(name = "size")
        protected Integer size;

        /**
         * Gets the value of the edge property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the edge property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEdge().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ProcessMap.Edges.Edge }
         * 
         * 
         */
        public List<ProcessMap.Edges.Edge> getEdge() {
            if (edge == null) {
                edge = new ArrayList<ProcessMap.Edges.Edge>();
            }
            return this.edge;
        }

        /**
         * Gets the value of the size property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getSize() {
            return size;
        }

        /**
         * Sets the value of the size property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setSize(Integer value) {
            this.size = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Frequency">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="total" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="case" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="maxRepetitions" type="{http://www.w3.org/2001/XMLSchema}int" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Duration">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="total" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="min" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="mean" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="median" type="{http://www.w3.org/2001/XMLSchema}int" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Layout">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="curve" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="labelX" type="{http://www.w3.org/2001/XMLSchema}double" />
         *                 &lt;attribute name="labelY" type="{http://www.w3.org/2001/XMLSchema}double" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="sourceIndex" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="targetIndex" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "frequency",
            "duration",
            "layout"
        })
        public static class Edge {

            @XmlElement(name = "Frequency", required = true)
            protected ProcessMap.Edges.Edge.Frequency frequency;
            @XmlElement(name = "Duration", required = true)
            protected ProcessMap.Edges.Edge.Duration duration;
            @XmlElement(name = "Layout", required = true)
            protected ProcessMap.Edges.Edge.Layout layout;
            @XmlAttribute(name = "sourceIndex")
            protected Integer sourceIndex;
            @XmlAttribute(name = "targetIndex")
            protected Integer targetIndex;
            @XmlAttribute(name = "type")
            protected String type;

            /**
             * Gets the value of the frequency property.
             * 
             * @return
             *     possible object is
             *     {@link ProcessMap.Edges.Edge.Frequency }
             *     
             */
            public ProcessMap.Edges.Edge.Frequency getFrequency() {
                return frequency;
            }

            /**
             * Sets the value of the frequency property.
             * 
             * @param value
             *     allowed object is
             *     {@link ProcessMap.Edges.Edge.Frequency }
             *     
             */
            public void setFrequency(ProcessMap.Edges.Edge.Frequency value) {
                this.frequency = value;
            }

            /**
             * Gets the value of the duration property.
             * 
             * @return
             *     possible object is
             *     {@link ProcessMap.Edges.Edge.Duration }
             *     
             */
            public ProcessMap.Edges.Edge.Duration getDuration() {
                return duration;
            }

            /**
             * Sets the value of the duration property.
             * 
             * @param value
             *     allowed object is
             *     {@link ProcessMap.Edges.Edge.Duration }
             *     
             */
            public void setDuration(ProcessMap.Edges.Edge.Duration value) {
                this.duration = value;
            }

            /**
             * Gets the value of the layout property.
             * 
             * @return
             *     possible object is
             *     {@link ProcessMap.Edges.Edge.Layout }
             *     
             */
            public ProcessMap.Edges.Edge.Layout getLayout() {
                return layout;
            }

            /**
             * Sets the value of the layout property.
             * 
             * @param value
             *     allowed object is
             *     {@link ProcessMap.Edges.Edge.Layout }
             *     
             */
            public void setLayout(ProcessMap.Edges.Edge.Layout value) {
                this.layout = value;
            }

            /**
             * Gets the value of the sourceIndex property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getSourceIndex() {
                return sourceIndex;
            }

            /**
             * Sets the value of the sourceIndex property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setSourceIndex(Integer value) {
                this.sourceIndex = value;
            }

            /**
             * Gets the value of the targetIndex property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getTargetIndex() {
                return targetIndex;
            }

            /**
             * Sets the value of the targetIndex property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setTargetIndex(Integer value) {
                this.targetIndex = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="total" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="min" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="mean" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="median" type="{http://www.w3.org/2001/XMLSchema}int" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Duration {

                @XmlAttribute(name = "total")
                protected Integer total;
                @XmlAttribute(name = "min")
                protected Integer min;
                @XmlAttribute(name = "max")
                protected Integer max;
                @XmlAttribute(name = "mean")
                protected Integer mean;
                @XmlAttribute(name = "median")
                protected Integer median;

                /**
                 * Gets the value of the total property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getTotal() {
                    return total;
                }

                /**
                 * Sets the value of the total property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setTotal(Integer value) {
                    this.total = value;
                }

                /**
                 * Gets the value of the min property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getMin() {
                    return min;
                }

                /**
                 * Sets the value of the min property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setMin(Integer value) {
                    this.min = value;
                }

                /**
                 * Gets the value of the max property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getMax() {
                    return max;
                }

                /**
                 * Sets the value of the max property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setMax(Integer value) {
                    this.max = value;
                }

                /**
                 * Gets the value of the mean property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getMean() {
                    return mean;
                }

                /**
                 * Sets the value of the mean property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setMean(Integer value) {
                    this.mean = value;
                }

                /**
                 * Gets the value of the median property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getMedian() {
                    return median;
                }

                /**
                 * Sets the value of the median property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setMedian(Integer value) {
                    this.median = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="total" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="case" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="maxRepetitions" type="{http://www.w3.org/2001/XMLSchema}int" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Frequency {

                @XmlAttribute(name = "total")
                protected Integer total;
                @XmlAttribute(name = "case")
                protected Integer _case;
                @XmlAttribute(name = "maxRepetitions")
                protected Integer maxRepetitions;

                /**
                 * Gets the value of the total property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getTotal() {
                    return total;
                }

                /**
                 * Sets the value of the total property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setTotal(Integer value) {
                    this.total = value;
                }

                /**
                 * Gets the value of the case property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getCase() {
                    return _case;
                }

                /**
                 * Sets the value of the case property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setCase(Integer value) {
                    this._case = value;
                }

                /**
                 * Gets the value of the maxRepetitions property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getMaxRepetitions() {
                    return maxRepetitions;
                }

                /**
                 * Sets the value of the maxRepetitions property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setMaxRepetitions(Integer value) {
                    this.maxRepetitions = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="curve" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="labelX" type="{http://www.w3.org/2001/XMLSchema}double" />
             *       &lt;attribute name="labelY" type="{http://www.w3.org/2001/XMLSchema}double" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Layout {

                @XmlAttribute(name = "curve")
                protected String curve;
                @XmlAttribute(name = "labelX")
                protected Double labelX;
                @XmlAttribute(name = "labelY")
                protected Double labelY;

                /**
                 * Gets the value of the curve property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCurve() {
                    return curve;
                }

                /**
                 * Sets the value of the curve property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCurve(String value) {
                    this.curve = value;
                }

                /**
                 * Gets the value of the labelX property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Double }
                 *     
                 */
                public Double getLabelX() {
                    return labelX;
                }

                /**
                 * Sets the value of the labelX property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Double }
                 *     
                 */
                public void setLabelX(Double value) {
                    this.labelX = value;
                }

                /**
                 * Gets the value of the labelY property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Double }
                 *     
                 */
                public Double getLabelY() {
                    return labelY;
                }

                /**
                 * Sets the value of the labelY property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Double }
                 *     
                 */
                public void setLabelY(Double value) {
                    this.labelY = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}double" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Layout {

        @XmlAttribute(name = "width")
        protected Double width;
        @XmlAttribute(name = "height")
        protected Double height;

        /**
         * Gets the value of the width property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getWidth() {
            return width;
        }

        /**
         * Sets the value of the width property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setWidth(Double value) {
            this.width = value;
        }

        /**
         * Gets the value of the height property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getHeight() {
            return height;
        }

        /**
         * Sets the value of the height property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setHeight(Double value) {
            this.height = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Node" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Frequency">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="total" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="case" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="start" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="end" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="maxRepetitions" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Duration">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="total" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="min" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="mean" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="median" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Layout">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                           &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                           &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                           &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="activity" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="StartNode">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Layout">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                           &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                           &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                           &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="EndNode">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Layout">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                           &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                           &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                           &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="size" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "node",
        "startNode",
        "endNode"
    })
    public static class Nodes {

        @XmlElement(name = "Node", required = true)
        protected List<ProcessMap.Nodes.Node> node;
        @XmlElement(name = "StartNode", required = true)
        protected ProcessMap.Nodes.StartNode startNode;
        @XmlElement(name = "EndNode", required = true)
        protected ProcessMap.Nodes.EndNode endNode;
        @XmlAttribute(name = "size")
        protected Integer size;

        /**
         * Gets the value of the node property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the node property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNode().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ProcessMap.Nodes.Node }
         * 
         * 
         */
        public List<ProcessMap.Nodes.Node> getNode() {
            if (node == null) {
                node = new ArrayList<ProcessMap.Nodes.Node>();
            }
            return this.node;
        }

        /**
         * Gets the value of the startNode property.
         * 
         * @return
         *     possible object is
         *     {@link ProcessMap.Nodes.StartNode }
         *     
         */
        public ProcessMap.Nodes.StartNode getStartNode() {
            return startNode;
        }

        /**
         * Sets the value of the startNode property.
         * 
         * @param value
         *     allowed object is
         *     {@link ProcessMap.Nodes.StartNode }
         *     
         */
        public void setStartNode(ProcessMap.Nodes.StartNode value) {
            this.startNode = value;
        }

        /**
         * Gets the value of the endNode property.
         * 
         * @return
         *     possible object is
         *     {@link ProcessMap.Nodes.EndNode }
         *     
         */
        public ProcessMap.Nodes.EndNode getEndNode() {
            return endNode;
        }

        /**
         * Sets the value of the endNode property.
         * 
         * @param value
         *     allowed object is
         *     {@link ProcessMap.Nodes.EndNode }
         *     
         */
        public void setEndNode(ProcessMap.Nodes.EndNode value) {
            this.endNode = value;
        }

        /**
         * Gets the value of the size property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getSize() {
            return size;
        }

        /**
         * Sets the value of the size property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setSize(Integer value) {
            this.size = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Layout">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}double" />
         *                 &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}double" />
         *                 &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}double" />
         *                 &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}double" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "layout"
        })
        public static class EndNode {

            @XmlElement(name = "Layout", required = true)
            protected ProcessMap.Nodes.EndNode.Layout layout;
            @XmlAttribute(name = "index")
            protected Integer index;

            /**
             * Gets the value of the layout property.
             * 
             * @return
             *     possible object is
             *     {@link ProcessMap.Nodes.EndNode.Layout }
             *     
             */
            public ProcessMap.Nodes.EndNode.Layout getLayout() {
                return layout;
            }

            /**
             * Sets the value of the layout property.
             * 
             * @param value
             *     allowed object is
             *     {@link ProcessMap.Nodes.EndNode.Layout }
             *     
             */
            public void setLayout(ProcessMap.Nodes.EndNode.Layout value) {
                this.layout = value;
            }

            /**
             * Gets the value of the index property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getIndex() {
                return index;
            }

            /**
             * Sets the value of the index property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setIndex(Integer value) {
                this.index = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}double" />
             *       &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}double" />
             *       &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}double" />
             *       &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}double" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Layout {

                @XmlAttribute(name = "x")
                protected Double x;
                @XmlAttribute(name = "y")
                protected Double y;
                @XmlAttribute(name = "width")
                protected Double width;
                @XmlAttribute(name = "height")
                protected Double height;

                /**
                 * Gets the value of the x property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Double }
                 *     
                 */
                public Double getX() {
                    return x;
                }

                /**
                 * Sets the value of the x property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Double }
                 *     
                 */
                public void setX(Double value) {
                    this.x = value;
                }

                /**
                 * Gets the value of the y property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Double }
                 *     
                 */
                public Double getY() {
                    return y;
                }

                /**
                 * Sets the value of the y property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Double }
                 *     
                 */
                public void setY(Double value) {
                    this.y = value;
                }

                /**
                 * Gets the value of the width property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Double }
                 *     
                 */
                public Double getWidth() {
                    return width;
                }

                /**
                 * Sets the value of the width property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Double }
                 *     
                 */
                public void setWidth(Double value) {
                    this.width = value;
                }

                /**
                 * Gets the value of the height property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Double }
                 *     
                 */
                public Double getHeight() {
                    return height;
                }

                /**
                 * Sets the value of the height property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Double }
                 *     
                 */
                public void setHeight(Double value) {
                    this.height = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Frequency">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="total" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="case" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="start" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="end" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="maxRepetitions" type="{http://www.w3.org/2001/XMLSchema}int" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Duration">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="total" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="min" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="mean" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="median" type="{http://www.w3.org/2001/XMLSchema}int" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Layout">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}double" />
         *                 &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}double" />
         *                 &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}double" />
         *                 &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}double" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="activity" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "frequency",
            "duration",
            "layout"
        })
        public static class Node {

            @XmlElement(name = "Frequency", required = true)
            protected ProcessMap.Nodes.Node.Frequency frequency;
            @XmlElement(name = "Duration", required = true)
            protected ProcessMap.Nodes.Node.Duration duration;
            @XmlElement(name = "Layout", required = true)
            protected ProcessMap.Nodes.Node.Layout layout;
            @XmlAttribute(name = "index")
            protected Integer index;
            @XmlAttribute(name = "activity")
            protected String activity;

            /**
             * Gets the value of the frequency property.
             * 
             * @return
             *     possible object is
             *     {@link ProcessMap.Nodes.Node.Frequency }
             *     
             */
            public ProcessMap.Nodes.Node.Frequency getFrequency() {
                return frequency;
            }

            /**
             * Sets the value of the frequency property.
             * 
             * @param value
             *     allowed object is
             *     {@link ProcessMap.Nodes.Node.Frequency }
             *     
             */
            public void setFrequency(ProcessMap.Nodes.Node.Frequency value) {
                this.frequency = value;
            }

            /**
             * Gets the value of the duration property.
             * 
             * @return
             *     possible object is
             *     {@link ProcessMap.Nodes.Node.Duration }
             *     
             */
            public ProcessMap.Nodes.Node.Duration getDuration() {
                return duration;
            }

            /**
             * Sets the value of the duration property.
             * 
             * @param value
             *     allowed object is
             *     {@link ProcessMap.Nodes.Node.Duration }
             *     
             */
            public void setDuration(ProcessMap.Nodes.Node.Duration value) {
                this.duration = value;
            }

            /**
             * Gets the value of the layout property.
             * 
             * @return
             *     possible object is
             *     {@link ProcessMap.Nodes.Node.Layout }
             *     
             */
            public ProcessMap.Nodes.Node.Layout getLayout() {
                return layout;
            }

            /**
             * Sets the value of the layout property.
             * 
             * @param value
             *     allowed object is
             *     {@link ProcessMap.Nodes.Node.Layout }
             *     
             */
            public void setLayout(ProcessMap.Nodes.Node.Layout value) {
                this.layout = value;
            }

            /**
             * Gets the value of the index property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getIndex() {
                return index;
            }

            /**
             * Sets the value of the index property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setIndex(Integer value) {
                this.index = value;
            }

            /**
             * Gets the value of the activity property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getActivity() {
                return activity;
            }

            /**
             * Sets the value of the activity property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setActivity(String value) {
                this.activity = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="total" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="min" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="mean" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="median" type="{http://www.w3.org/2001/XMLSchema}int" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Duration {

                @XmlAttribute(name = "total")
                protected Integer total;
                @XmlAttribute(name = "min")
                protected Integer min;
                @XmlAttribute(name = "max")
                protected Integer max;
                @XmlAttribute(name = "mean")
                protected Integer mean;
                @XmlAttribute(name = "median")
                protected Integer median;

                /**
                 * Gets the value of the total property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getTotal() {
                    return total;
                }

                /**
                 * Sets the value of the total property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setTotal(Integer value) {
                    this.total = value;
                }

                /**
                 * Gets the value of the min property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getMin() {
                    return min;
                }

                /**
                 * Sets the value of the min property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setMin(Integer value) {
                    this.min = value;
                }

                /**
                 * Gets the value of the max property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getMax() {
                    return max;
                }

                /**
                 * Sets the value of the max property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setMax(Integer value) {
                    this.max = value;
                }

                /**
                 * Gets the value of the mean property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getMean() {
                    return mean;
                }

                /**
                 * Sets the value of the mean property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setMean(Integer value) {
                    this.mean = value;
                }

                /**
                 * Gets the value of the median property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getMedian() {
                    return median;
                }

                /**
                 * Sets the value of the median property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setMedian(Integer value) {
                    this.median = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="total" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="case" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="start" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="end" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="maxRepetitions" type="{http://www.w3.org/2001/XMLSchema}int" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Frequency {

                @XmlAttribute(name = "total")
                protected Integer total;
                @XmlAttribute(name = "case")
                protected Integer _case;
                @XmlAttribute(name = "start")
                protected Integer start;
                @XmlAttribute(name = "end")
                protected Integer end;
                @XmlAttribute(name = "maxRepetitions")
                protected Integer maxRepetitions;

                /**
                 * Gets the value of the total property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getTotal() {
                    return total;
                }

                /**
                 * Sets the value of the total property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setTotal(Integer value) {
                    this.total = value;
                }

                /**
                 * Gets the value of the case property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getCase() {
                    return _case;
                }

                /**
                 * Sets the value of the case property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setCase(Integer value) {
                    this._case = value;
                }

                /**
                 * Gets the value of the start property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getStart() {
                    return start;
                }

                /**
                 * Sets the value of the start property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setStart(Integer value) {
                    this.start = value;
                }

                /**
                 * Gets the value of the end property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getEnd() {
                    return end;
                }

                /**
                 * Sets the value of the end property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setEnd(Integer value) {
                    this.end = value;
                }

                /**
                 * Gets the value of the maxRepetitions property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getMaxRepetitions() {
                    return maxRepetitions;
                }

                /**
                 * Sets the value of the maxRepetitions property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setMaxRepetitions(Integer value) {
                    this.maxRepetitions = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}double" />
             *       &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}double" />
             *       &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}double" />
             *       &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}double" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Layout {

                @XmlAttribute(name = "x")
                protected Double x;
                @XmlAttribute(name = "y")
                protected Double y;
                @XmlAttribute(name = "width")
                protected Double width;
                @XmlAttribute(name = "height")
                protected Double height;

                /**
                 * Gets the value of the x property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Double }
                 *     
                 */
                public Double getX() {
                    return x;
                }

                /**
                 * Sets the value of the x property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Double }
                 *     
                 */
                public void setX(Double value) {
                    this.x = value;
                }

                /**
                 * Gets the value of the y property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Double }
                 *     
                 */
                public Double getY() {
                    return y;
                }

                /**
                 * Sets the value of the y property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Double }
                 *     
                 */
                public void setY(Double value) {
                    this.y = value;
                }

                /**
                 * Gets the value of the width property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Double }
                 *     
                 */
                public Double getWidth() {
                    return width;
                }

                /**
                 * Sets the value of the width property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Double }
                 *     
                 */
                public void setWidth(Double value) {
                    this.width = value;
                }

                /**
                 * Gets the value of the height property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Double }
                 *     
                 */
                public Double getHeight() {
                    return height;
                }

                /**
                 * Sets the value of the height property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Double }
                 *     
                 */
                public void setHeight(Double value) {
                    this.height = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Layout">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}double" />
         *                 &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}double" />
         *                 &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}double" />
         *                 &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}double" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "layout"
        })
        public static class StartNode {

            @XmlElement(name = "Layout", required = true)
            protected ProcessMap.Nodes.StartNode.Layout layout;
            @XmlAttribute(name = "index")
            protected Integer index;

            /**
             * Gets the value of the layout property.
             * 
             * @return
             *     possible object is
             *     {@link ProcessMap.Nodes.StartNode.Layout }
             *     
             */
            public ProcessMap.Nodes.StartNode.Layout getLayout() {
                return layout;
            }

            /**
             * Sets the value of the layout property.
             * 
             * @param value
             *     allowed object is
             *     {@link ProcessMap.Nodes.StartNode.Layout }
             *     
             */
            public void setLayout(ProcessMap.Nodes.StartNode.Layout value) {
                this.layout = value;
            }

            /**
             * Gets the value of the index property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getIndex() {
                return index;
            }

            /**
             * Sets the value of the index property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setIndex(Integer value) {
                this.index = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}double" />
             *       &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}double" />
             *       &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}double" />
             *       &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}double" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Layout {

                @XmlAttribute(name = "x")
                protected Double x;
                @XmlAttribute(name = "y")
                protected Double y;
                @XmlAttribute(name = "width")
                protected Double width;
                @XmlAttribute(name = "height")
                protected Double height;

                /**
                 * Gets the value of the x property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Double }
                 *     
                 */
                public Double getX() {
                    return x;
                }

                /**
                 * Sets the value of the x property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Double }
                 *     
                 */
                public void setX(Double value) {
                    this.x = value;
                }

                /**
                 * Gets the value of the y property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Double }
                 *     
                 */
                public Double getY() {
                    return y;
                }

                /**
                 * Sets the value of the y property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Double }
                 *     
                 */
                public void setY(Double value) {
                    this.y = value;
                }

                /**
                 * Gets the value of the width property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Double }
                 *     
                 */
                public Double getWidth() {
                    return width;
                }

                /**
                 * Sets the value of the width property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Double }
                 *     
                 */
                public void setWidth(Double value) {
                    this.width = value;
                }

                /**
                 * Gets the value of the height property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Double }
                 *     
                 */
                public Double getHeight() {
                    return height;
                }

                /**
                 * Sets the value of the height property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Double }
                 *     
                 */
                public void setHeight(Double value) {
                    this.height = value;
                }

            }

        }

    }

}
