//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.29 at 10:00:32 PM CET 
//


package org.opengroup.xsd.archimate;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.opengroup.xsd.archimate package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Model_QNAME = new QName("http://www.opengroup.org/xsd/archimate", "model");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.opengroup.xsd.archimate
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RgbColorType }
     * 
     */
    public RgbColorType createRgbColorType() {
        return new RgbColorType();
    }

    /**
     * Create an instance of {@link DataObject }
     * 
     */
    public DataObject createDataObject() {
        return new DataObject();
    }

    /**
     * Create an instance of {@link RelationshipType }
     * 
     */
    public RelationshipType createRelationshipType() {
        return new RelationshipType();
    }

    /**
     * Create an instance of {@link ApplicationInteraction }
     * 
     */
    public ApplicationInteraction createApplicationInteraction() {
        return new ApplicationInteraction();
    }

    /**
     * Create an instance of {@link ViewsType }
     * 
     */
    public ViewsType createViewsType() {
        return new ViewsType();
    }

    /**
     * Create an instance of {@link BusinessService }
     * 
     */
    public BusinessService createBusinessService() {
        return new BusinessService();
    }

    /**
     * Create an instance of {@link Contract }
     * 
     */
    public Contract createContract() {
        return new Contract();
    }

    /**
     * Create an instance of {@link Meaning }
     * 
     */
    public Meaning createMeaning() {
        return new Meaning();
    }

    /**
     * Create an instance of {@link ModelType }
     * 
     */
    public ModelType createModelType() {
        return new ModelType();
    }

    /**
     * Create an instance of {@link InfrastructureFunction }
     * 
     */
    public InfrastructureFunction createInfrastructureFunction() {
        return new InfrastructureFunction();
    }

    /**
     * Create an instance of {@link WorkPackage }
     * 
     */
    public WorkPackage createWorkPackage() {
        return new WorkPackage();
    }

    /**
     * Create an instance of {@link Device }
     * 
     */
    public Device createDevice() {
        return new Device();
    }

    /**
     * Create an instance of {@link Requirement }
     * 
     */
    public Requirement createRequirement() {
        return new Requirement();
    }

    /**
     * Create an instance of {@link BusinessInterface }
     * 
     */
    public BusinessInterface createBusinessInterface() {
        return new BusinessInterface();
    }

    /**
     * Create an instance of {@link InfrastructureService }
     * 
     */
    public InfrastructureService createInfrastructureService() {
        return new InfrastructureService();
    }

    /**
     * Create an instance of {@link OrganizationType }
     * 
     */
    public OrganizationType createOrganizationType() {
        return new OrganizationType();
    }

    /**
     * Create an instance of {@link Plateau }
     * 
     */
    public Plateau createPlateau() {
        return new Plateau();
    }

    /**
     * Create an instance of {@link LangStringType }
     * 
     */
    public LangStringType createLangStringType() {
        return new LangStringType();
    }

    /**
     * Create an instance of {@link MetadataType }
     * 
     */
    public MetadataType createMetadataType() {
        return new MetadataType();
    }

    /**
     * Create an instance of {@link ItemType }
     * 
     */
    public ItemType createItemType() {
        return new ItemType();
    }

    /**
     * Create an instance of {@link AssignmentRelationship }
     * 
     */
    public AssignmentRelationship createAssignmentRelationship() {
        return new AssignmentRelationship();
    }

    /**
     * Create an instance of {@link PropertyDefinitionType }
     * 
     */
    public PropertyDefinitionType createPropertyDefinitionType() {
        return new PropertyDefinitionType();
    }

    /**
     * Create an instance of {@link UsedByRelationship }
     * 
     */
    public UsedByRelationship createUsedByRelationship() {
        return new UsedByRelationship();
    }

    /**
     * Create an instance of {@link BusinessRole }
     * 
     */
    public BusinessRole createBusinessRole() {
        return new BusinessRole();
    }

    /**
     * Create an instance of {@link Goal }
     * 
     */
    public Goal createGoal() {
        return new Goal();
    }

    /**
     * Create an instance of {@link RealisationRelationship }
     * 
     */
    public RealisationRelationship createRealisationRelationship() {
        return new RealisationRelationship();
    }

    /**
     * Create an instance of {@link AccessRelationship }
     * 
     */
    public AccessRelationship createAccessRelationship() {
        return new AccessRelationship();
    }

    /**
     * Create an instance of {@link Constraint }
     * 
     */
    public Constraint createConstraint() {
        return new Constraint();
    }

    /**
     * Create an instance of {@link BusinessActor }
     * 
     */
    public BusinessActor createBusinessActor() {
        return new BusinessActor();
    }

    /**
     * Create an instance of {@link FlowRelationship }
     * 
     */
    public FlowRelationship createFlowRelationship() {
        return new FlowRelationship();
    }

    /**
     * Create an instance of {@link StyleType }
     * 
     */
    public StyleType createStyleType() {
        return new StyleType();
    }

    /**
     * Create an instance of {@link InfluenceRelationship }
     * 
     */
    public InfluenceRelationship createInfluenceRelationship() {
        return new InfluenceRelationship();
    }

    /**
     * Create an instance of {@link Artifact }
     * 
     */
    public Artifact createArtifact() {
        return new Artifact();
    }

    /**
     * Create an instance of {@link PropertiesDefinitionsType }
     * 
     */
    public PropertiesDefinitionsType createPropertiesDefinitionsType() {
        return new PropertiesDefinitionsType();
    }

    /**
     * Create an instance of {@link BendpointType }
     * 
     */
    public BendpointType createBendpointType() {
        return new BendpointType();
    }

    /**
     * Create an instance of {@link RelationshipsType }
     * 
     */
    public RelationshipsType createRelationshipsType() {
        return new RelationshipsType();
    }

    /**
     * Create an instance of {@link BusinessObject }
     * 
     */
    public BusinessObject createBusinessObject() {
        return new BusinessObject();
    }

    /**
     * Create an instance of {@link AssociationRelationship }
     * 
     */
    public AssociationRelationship createAssociationRelationship() {
        return new AssociationRelationship();
    }

    /**
     * Create an instance of {@link ElementType }
     * 
     */
    public ElementType createElementType() {
        return new ElementType();
    }

    /**
     * Create an instance of {@link PropertiesType }
     * 
     */
    public PropertiesType createPropertiesType() {
        return new PropertiesType();
    }

    /**
     * Create an instance of {@link ApplicationService }
     * 
     */
    public ApplicationService createApplicationService() {
        return new ApplicationService();
    }

    /**
     * Create an instance of {@link FontType }
     * 
     */
    public FontType createFontType() {
        return new FontType();
    }

    /**
     * Create an instance of {@link BusinessInteraction }
     * 
     */
    public BusinessInteraction createBusinessInteraction() {
        return new BusinessInteraction();
    }

    /**
     * Create an instance of {@link Value }
     * 
     */
    public Value createValue() {
        return new Value();
    }

    /**
     * Create an instance of {@link BusinessFunction }
     * 
     */
    public BusinessFunction createBusinessFunction() {
        return new BusinessFunction();
    }

    /**
     * Create an instance of {@link ApplicationInterface }
     * 
     */
    public ApplicationInterface createApplicationInterface() {
        return new ApplicationInterface();
    }

    /**
     * Create an instance of {@link Product }
     * 
     */
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link AggregationRelationship }
     * 
     */
    public AggregationRelationship createAggregationRelationship() {
        return new AggregationRelationship();
    }

    /**
     * Create an instance of {@link Principle }
     * 
     */
    public Principle createPrinciple() {
        return new Principle();
    }

    /**
     * Create an instance of {@link SystemSoftware }
     * 
     */
    public SystemSoftware createSystemSoftware() {
        return new SystemSoftware();
    }

    /**
     * Create an instance of {@link PropertyType }
     * 
     */
    public PropertyType createPropertyType() {
        return new PropertyType();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link CommunicationPath }
     * 
     */
    public CommunicationPath createCommunicationPath() {
        return new CommunicationPath();
    }

    /**
     * Create an instance of {@link Gap }
     * 
     */
    public Gap createGap() {
        return new Gap();
    }

    /**
     * Create an instance of {@link ApplicationFunction }
     * 
     */
    public ApplicationFunction createApplicationFunction() {
        return new ApplicationFunction();
    }

    /**
     * Create an instance of {@link Assessment }
     * 
     */
    public Assessment createAssessment() {
        return new Assessment();
    }

    /**
     * Create an instance of {@link Network }
     * 
     */
    public Network createNetwork() {
        return new Network();
    }

    /**
     * Create an instance of {@link SpecialisationRelationship }
     * 
     */
    public SpecialisationRelationship createSpecialisationRelationship() {
        return new SpecialisationRelationship();
    }

    /**
     * Create an instance of {@link TriggeringRelationship }
     * 
     */
    public TriggeringRelationship createTriggeringRelationship() {
        return new TriggeringRelationship();
    }

    /**
     * Create an instance of {@link CompositionRelationship }
     * 
     */
    public CompositionRelationship createCompositionRelationship() {
        return new CompositionRelationship();
    }

    /**
     * Create an instance of {@link ConnectionType }
     * 
     */
    public ConnectionType createConnectionType() {
        return new ConnectionType();
    }

    /**
     * Create an instance of {@link Stakeholder }
     * 
     */
    public Stakeholder createStakeholder() {
        return new Stakeholder();
    }

    /**
     * Create an instance of {@link Junction }
     * 
     */
    public Junction createJunction() {
        return new Junction();
    }

    /**
     * Create an instance of {@link Deliverable }
     * 
     */
    public Deliverable createDeliverable() {
        return new Deliverable();
    }

    /**
     * Create an instance of {@link InfrastructureInterface }
     * 
     */
    public InfrastructureInterface createInfrastructureInterface() {
        return new InfrastructureInterface();
    }

    /**
     * Create an instance of {@link ApplicationComponent }
     * 
     */
    public ApplicationComponent createApplicationComponent() {
        return new ApplicationComponent();
    }

    /**
     * Create an instance of {@link ViewType }
     * 
     */
    public ViewType createViewType() {
        return new ViewType();
    }

    /**
     * Create an instance of {@link ApplicationCollaboration }
     * 
     */
    public ApplicationCollaboration createApplicationCollaboration() {
        return new ApplicationCollaboration();
    }

    /**
     * Create an instance of {@link Representation }
     * 
     */
    public Representation createRepresentation() {
        return new Representation();
    }

    /**
     * Create an instance of {@link BusinessProcess }
     * 
     */
    public BusinessProcess createBusinessProcess() {
        return new BusinessProcess();
    }

    /**
     * Create an instance of {@link Node }
     * 
     */
    public Node createNode() {
        return new Node();
    }

    /**
     * Create an instance of {@link BusinessEvent }
     * 
     */
    public BusinessEvent createBusinessEvent() {
        return new BusinessEvent();
    }

    /**
     * Create an instance of {@link NodeType }
     * 
     */
    public NodeType createNodeType() {
        return new NodeType();
    }

    /**
     * Create an instance of {@link BusinessCollaboration }
     * 
     */
    public BusinessCollaboration createBusinessCollaboration() {
        return new BusinessCollaboration();
    }

    /**
     * Create an instance of {@link ElementsType }
     * 
     */
    public ElementsType createElementsType() {
        return new ElementsType();
    }

    /**
     * Create an instance of {@link Driver }
     * 
     */
    public Driver createDriver() {
        return new Driver();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModelType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengroup.org/xsd/archimate", name = "model")
    public JAXBElement<ModelType> createModel(ModelType value) {
        return new JAXBElement<ModelType>(_Model_QNAME, ModelType.class, null, value);
    }

}
