//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.29 at 10:00:32 PM CET 
//


package org.opengroup.xsd.archimate;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for viewpointsEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="viewpointsEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Introductory"/>
 *     &lt;enumeration value="Organization"/>
 *     &lt;enumeration value="Actor Co-operation"/>
 *     &lt;enumeration value="Business Function"/>
 *     &lt;enumeration value="Business Process"/>
 *     &lt;enumeration value="Business Process Co-operation"/>
 *     &lt;enumeration value="Product"/>
 *     &lt;enumeration value="Application Behavior"/>
 *     &lt;enumeration value="Application Co-operation"/>
 *     &lt;enumeration value="Application Structure"/>
 *     &lt;enumeration value="Application Usage"/>
 *     &lt;enumeration value="Infrastructure"/>
 *     &lt;enumeration value="Infrastructure Usage"/>
 *     &lt;enumeration value="Implementation and Deployment"/>
 *     &lt;enumeration value="Information Structure"/>
 *     &lt;enumeration value="Service Realization"/>
 *     &lt;enumeration value="Layered"/>
 *     &lt;enumeration value="Landscape Map"/>
 *     &lt;enumeration value="Stakeholder"/>
 *     &lt;enumeration value="Goal Realization"/>
 *     &lt;enumeration value="Goal Contribution"/>
 *     &lt;enumeration value="Principles"/>
 *     &lt;enumeration value="Requirements Realization"/>
 *     &lt;enumeration value="Motivation"/>
 *     &lt;enumeration value="Project"/>
 *     &lt;enumeration value="Migration"/>
 *     &lt;enumeration value="Implementation and Migration"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "viewpointsEnum")
@XmlEnum
public enum ViewpointsEnum {

    @XmlEnumValue("Introductory")
    INTRODUCTORY("Introductory"),
    @XmlEnumValue("Organization")
    ORGANIZATION("Organization"),
    @XmlEnumValue("Actor Co-operation")
    ACTOR_CO_OPERATION("Actor Co-operation"),
    @XmlEnumValue("Business Function")
    BUSINESS_FUNCTION("Business Function"),
    @XmlEnumValue("Business Process")
    BUSINESS_PROCESS("Business Process"),
    @XmlEnumValue("Business Process Co-operation")
    BUSINESS_PROCESS_CO_OPERATION("Business Process Co-operation"),
    @XmlEnumValue("Product")
    PRODUCT("Product"),
    @XmlEnumValue("Application Behavior")
    APPLICATION_BEHAVIOR("Application Behavior"),
    @XmlEnumValue("Application Co-operation")
    APPLICATION_CO_OPERATION("Application Co-operation"),
    @XmlEnumValue("Application Structure")
    APPLICATION_STRUCTURE("Application Structure"),
    @XmlEnumValue("Application Usage")
    APPLICATION_USAGE("Application Usage"),
    @XmlEnumValue("Infrastructure")
    INFRASTRUCTURE("Infrastructure"),
    @XmlEnumValue("Infrastructure Usage")
    INFRASTRUCTURE_USAGE("Infrastructure Usage"),
    @XmlEnumValue("Implementation and Deployment")
    IMPLEMENTATION_AND_DEPLOYMENT("Implementation and Deployment"),
    @XmlEnumValue("Information Structure")
    INFORMATION_STRUCTURE("Information Structure"),
    @XmlEnumValue("Service Realization")
    SERVICE_REALIZATION("Service Realization"),
    @XmlEnumValue("Layered")
    LAYERED("Layered"),
    @XmlEnumValue("Landscape Map")
    LANDSCAPE_MAP("Landscape Map"),
    @XmlEnumValue("Stakeholder")
    STAKEHOLDER("Stakeholder"),
    @XmlEnumValue("Goal Realization")
    GOAL_REALIZATION("Goal Realization"),
    @XmlEnumValue("Goal Contribution")
    GOAL_CONTRIBUTION("Goal Contribution"),
    @XmlEnumValue("Principles")
    PRINCIPLES("Principles"),
    @XmlEnumValue("Requirements Realization")
    REQUIREMENTS_REALIZATION("Requirements Realization"),
    @XmlEnumValue("Motivation")
    MOTIVATION("Motivation"),
    @XmlEnumValue("Project")
    PROJECT("Project"),
    @XmlEnumValue("Migration")
    MIGRATION("Migration"),
    @XmlEnumValue("Implementation and Migration")
    IMPLEMENTATION_AND_MIGRATION("Implementation and Migration");
    private final String value;

    ViewpointsEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ViewpointsEnum fromValue(String v) {
        for (ViewpointsEnum c: ViewpointsEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
