//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.29 at 10:00:32 PM CET 
//


package org.opengroup.xsd.archimate;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 RGB Color type.
 *                 The r, g, b attributes range from 0 - 255.
 *                 The a (alpha) transparency attribute is optional. 0 = full transparency, 100 = opaque.
 *             
 * 
 * <p>Java class for rgbColorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rgbColorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="r" use="required" type="{http://www.opengroup.org/xsd/archimate}rgbValueType" />
 *       &lt;attribute name="g" use="required" type="{http://www.opengroup.org/xsd/archimate}rgbValueType" />
 *       &lt;attribute name="b" use="required" type="{http://www.opengroup.org/xsd/archimate}rgbValueType" />
 *       &lt;attribute name="a">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedByte">
 *             &lt;minInclusive value="0"/>
 *             &lt;maxInclusive value="100"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rgbColorType")
public class RgbColorType {

    @XmlAttribute(name = "r", required = true)
    protected short r;
    @XmlAttribute(name = "g", required = true)
    protected short g;
    @XmlAttribute(name = "b", required = true)
    protected short b;
    @XmlAttribute(name = "a")
    protected Short a;

    /**
     * Gets the value of the r property.
     * 
     */
    public short getR() {
        return r;
    }

    /**
     * Sets the value of the r property.
     * 
     */
    public void setR(short value) {
        this.r = value;
    }

    /**
     * Gets the value of the g property.
     * 
     */
    public short getG() {
        return g;
    }

    /**
     * Sets the value of the g property.
     * 
     */
    public void setG(short value) {
        this.g = value;
    }

    /**
     * Gets the value of the b property.
     * 
     */
    public short getB() {
        return b;
    }

    /**
     * Sets the value of the b property.
     * 
     */
    public void setB(short value) {
        this.b = value;
    }

    /**
     * Gets the value of the a property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getA() {
        return a;
    }

    /**
     * Sets the value of the a property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setA(Short value) {
        this.a = value;
    }

}
